#!/usr/bin/env bash

set -euo pipefail  # Exit on error, undefined variables, and pipe failures

# ============================================================================
# AUTOMATED WORKFLOW - MOLECULAR DYNAMICS FILM CASTING
# Simulates gradual solvent evaporation through MD cycles
# ============================================================================

# ------------ CONFIGURATION ------------
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly CONFIG_FILE="${SCRIPT_DIR}/evaporate.conf"

# Load configuration from file
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
fi

# Default configuration values
SEG_NS="${SEG_NS:-1}"                          # Duration of each cycle (ns)
CYCLES="${CYCLES:-20}"                         # Total number of cycles
TOP="${TOP:-film.top}"                         # Initial topology
GRO="${GRO:-npt.gro}"                         # Initial structure from NPT
CPT="${CPT:-npt.cpt}"                         # Initial checkpoint
LOG_FILE="${LOG_FILE:-evaporate.log}"         # Log file
OUT_FILM="${OUT_FILM:-final_film}"            # Final film name
PYTHON="${PYTHON:-python3}"                    # Python with MDAnalysis

# MDP file names (generated by prepare_evaporation.py)
MDP_MD="md.mdp"
MDP_NVT="nvt_eq.mdp"
MDP_NPT="npt_eq.mdp"
MDP_EM="em.mdp"
MDP_ANNEAL="md_anneling.mdp"

# Constants
readonly RLIST_BUFFER=0.3                      # Safety buffer for rlist
readonly EVAP_PLANE=$(awk -v n="${CYCLES}" 'BEGIN {printf "%.6f", (0.01)^(1/n)}')

# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

# ----------------------------------------------------------------------------
# Function: log_message
# Description: Logs messages to file and displays on terminal
# Parameters: $1 = message
# ----------------------------------------------------------------------------
log_message() {
    echo "$1" | tee -a "$LOG_FILE"
}

# ----------------------------------------------------------------------------
# Function: log_error
# Description: Logs error and exits script
# Parameters: $1 = error message
# ----------------------------------------------------------------------------
log_error() {
    echo "ERROR: $1" | tee -a "$LOG_FILE" >&2
    exit 1
}

# ----------------------------------------------------------------------------
# Function: check_mdp_files
# Description: Verifies that all required MDP files exist
# ----------------------------------------------------------------------------
check_mdp_files() {
    local missing_files=()
    
    for mdp in "$MDP_EM" "$MDP_NVT" "$MDP_NPT" "$MDP_MD" "$MDP_ANNEAL"; do
        if [[ ! -f "$mdp" ]]; then
            missing_files+=("$mdp")
        fi
    done
    
    if [[ ${#missing_files[@]} -gt 0 ]]; then
        log_error "Missing MDP files: ${missing_files[*]}"
    fi    
}
# ----------------------------------------------------------------------------
# Function: get_box_dimensions
# Description: Extracts box dimensions from .gro file
# Parameters: $1 = .gro file
# Returns: boxX boxY boxZ (via echo)
# ----------------------------------------------------------------------------
get_box_dimensions() {
    local gro_file="$1"
    awk 'END {print $1, $2, $3}' "$gro_file"
}

# ----------------------------------------------------------------------------
# Function: get_rlist_value
# Description: Gets actual rlist value from log or TPR
# Parameters: $1 = step tag
# Returns: rlist value
# ----------------------------------------------------------------------------
get_rlist_value() {
    local tag="$1"
    local rlist_real
    
    # Try to get from log
    rlist_real=$(grep "rlist from" "step${tag}_npt.log" 2>/dev/null | tail -1 | awk '{print $11}' || echo "")
    
    # If not found in log, use TPR
    if [[ -z "$rlist_real" ]]; then
        log_message "[WARNING] rlist not found in log. Using TPR value."
        rlist_real=$(gmx dump -s "step${tag}_npt.tpr" 2>/dev/null | grep "rlist" | head -1 | awk '{print $3}' || echo "1.2")
    fi
    
    echo "$rlist_real"
}

# ----------------------------------------------------------------------------
# Function: check_and_fix_box_height
# Description: Checks and fixes box height if necessary
# Parameters: $1 = .gro file, $2 = step tag
# ----------------------------------------------------------------------------
check_and_fix_box_height() {
    local gro_file="$1"
    local tag="$2"
    
    log_message ">>> Checking simulation box height..."
    
    # Get dimensions
    read -r boxX boxY boxZ <<< "$(get_box_dimensions "$gro_file")"
    local zmax=$(tail -n 1 "$gro_file" | awk '{print $3}')
    
    # Calculate minimum safe height
    local rlist_real=$(get_rlist_value "$tag")
    local minZ=$(echo "$rlist_real * 2 + $RLIST_BUFFER" | bc -l)
    
    # Check if adjustment is needed
    local needs_fix=$(echo "$zmax < $minZ" | bc -l)
    
    if [[ "$needs_fix" -eq 1 ]]; then
        log_message ">>> Z-height ($zmax nm) too small. Correcting to ${minZ} nm"
        
        # Backup original file
        cp "$gro_file" "old_${gro_file}"
        
        # Adjust box
        gmx editconf -f "$gro_file" -o newbox.gro -c -box "$boxX" "$boxY" "$minZ" &>/dev/null
        
        # Replace file
        cp newbox.gro "box_fixed_${tag}.gro"
        cp newbox.gro "$gro_file"
        rm -f newbox.gro
        
        # Check consistency
        check_topology_consistency "$gro_file" "${TOP}"
    else
        log_message "    Z-height ($zmax nm) adequate (minimum: ${minZ} nm)"
    fi
}

# ----------------------------------------------------------------------------
# Function: check_topology_consistency
# Description: Verifies consistency between .gro and .top
# Parameters: $1 = .gro file, $2 = .top file
# ----------------------------------------------------------------------------
check_topology_consistency() {
    local gro_file="$1"
    local top_file="$2"
    
    local n_atoms_gro=$(tail -n +3 "$gro_file" | wc -l)
    local n_sol_top=$(grep "^SOL" "$top_file" | awk '{print $2}' || echo "0")
    
    log_message "[INFO] Consistency check:"
    log_message "    Atoms in .gro: $n_atoms_gro"
    log_message "    SOL molecules in .top: $n_sol_top"
}

# ----------------------------------------------------------------------------
# Function: run_equilibration
# Description: Executes energy minimization, NVT and NPT
# Parameters: $1 = step tag, $2 = input gro, $3 = input top
# ----------------------------------------------------------------------------
run_equilibration() {
    local tag="$1"
    local input_gro="$2"
    local input_top="$3"
    
    log_message ">>> Running equilibration for step ${tag}..."
    
    # Energy minimization
    log_message "    - Energy minimization"
    gmx grompp -f "$MDP_EM" -c "$input_gro" -p "$input_top" \
               -o "step${tag}_min.tpr" -maxwarn 10 &>/dev/null || log_error "grompp failed (EM)"
    gmx mdrun -deffnm "step${tag}_min" -v &>/dev/null || log_error "mdrun failed (EM)"
    
    # NVT
    log_message "    - NVT equilibration"
    gmx grompp -f "$MDP_NVT" -c "step${tag}_min.gro" -r "step${tag}_min.gro" \
               -p "$input_top" -o "step${tag}_nvt.tpr" -maxwarn 10 &>/dev/null || log_error "grompp failed (NVT)"
    gmx mdrun -deffnm "step${tag}_nvt" -v &>/dev/null || log_error "mdrun failed (NVT)"
    
    # NPT
    log_message "    - NPT equilibration"
    gmx grompp -f "$MDP_NPT" -c "step${tag}_nvt.gro" -t "step${tag}_nvt.cpt" \
               -r "step${tag}_nvt.gro" -p "$input_top" -o "step${tag}_npt.tpr" \
               -maxwarn 10 &>/dev/null || log_error "grompp failed (NPT)"
    gmx mdrun -deffnm "step${tag}_npt" -v &>/dev/null || log_error "mdrun failed (NPT)"
    
    log_message ">>> Equilibration completed"
}

# ----------------------------------------------------------------------------
# Function: run_production_md
# Description: Executes production molecular dynamics
# Parameters: $1 = tag, $2 = input gro, $3 = input cpt, $4 = input top
# ----------------------------------------------------------------------------
run_production_md() {
    local tag="$1"
    local input_gro="$2"
    local input_cpt="$3"
    local input_top="$4"
    
    log_message ">>> Running production MD (${SEG_NS} ns)..."
    
    # Prepare TPR
    gmx grompp -f "$MDP_MD" -c "$input_gro" -t "$input_cpt" -p "$input_top" \
               -o "step${tag}.tpr" -maxwarn 10 &>/dev/null || log_error "grompp failed (MD)"
    
    # Run MD
    gmx mdrun -deffnm "step${tag}" -v || log_error "mdrun failed (MD) in cycle $tag"
    
    # Extract last frame
    echo 0 | gmx trjconv -f "step${tag}.trr" -s "step${tag}.tpr" \
                          -dump $((SEG_NS * 1000)) -o "step${tag}_last.gro" \
                          -pbc mol -ur compact &>/dev/null
    
    # Remove trajectory to save space
    rm -f "step${tag}.trr"
    
    log_message ">>> Production MD completed"
}

# ----------------------------------------------------------------------------
# Function: evaporate_solvent
# Description: Removes solvent using Python script
# Parameters: $1 = step tag
# ----------------------------------------------------------------------------
evaporate_solvent() {
    local tag="$1"
    
    log_message ">>> Evaporating solvent (planar fraction=${EVAP_PLANE})..."
    
    "$PYTHON" evaporate.py "step${tag}_last.gro" "$TOP" \
              "step${tag}_post.gro" "step${tag}_post.top" "$EVAP_PLANE" \
              || log_error "Evaporation failed in cycle $tag"
    
    log_message ">>> Evaporation completed"
}

# ============================================================================
# MAIN SIMULATION LOOP
# ============================================================================

main() {
    log_message "========================================"
    log_message "STARTING FILM CASTING SIMULATION"
    log_message "========================================"
    log_message "Configuration:"
    log_message "  - Cycles: $CYCLES"
    log_message "  - Duration per cycle: ${SEG_NS} ns"
    log_message "  - Evaporation fraction: ${EVAP_PLANE}"
    log_message ""
    
    # Check for MDP files
    check_mdp_files
    
    # Main loop
    for ((i=0; i<CYCLES; i++)); do
        local tag=$(printf "%d" $i)
        
        log_message ""
        log_message "========================================"
        log_message "CYCLE $i of $((CYCLES-1))"
        log_message "========================================"
        
        # Check if already processed
        if [[ -f "step${tag}_last.gro" ]]; then
            log_message "Cycle $i already processed. Skipping..."
            continue
        fi
        
        # Define input files
        if [[ $i -eq 0 ]]; then
            # First cycle: use initial files
            local current_gro="$GRO"
            local current_cpt="$CPT"
            local current_top="$TOP"
        else
            # Subsequent cycles: use output from previous cycle
            local prev_tag=$(printf "%d" $((i-1)))
            local current_gro="step${prev_tag}_npt.gro"
            local current_cpt="step${prev_tag}_npt.cpt"
            local current_top="step${prev_tag}_post.top"
            
            # If NPT doesn't exist, run equilibration
            if [[ ! -f "$current_gro" ]]; then
                log_message "Previous NPT not found. Running equilibration..."
                current_gro="step${prev_tag}_post.gro"
                run_equilibration "$prev_tag" "$current_gro" "$current_top"
                current_gro="step${prev_tag}_npt.gro"
                current_cpt="step${prev_tag}_npt.cpt"
            fi
            
            # Check and fix box height
            check_and_fix_box_height "$current_gro" "$prev_tag"
        fi
        
        # Run production MD
        run_production_md "$tag" "$current_gro" "$current_cpt" "$current_top"
        
        # Evaporate solvent
        evaporate_solvent "$tag"
        
        # Check and fix height after evaporation
        check_and_fix_box_height "step${tag}_post.gro" "$tag"
        
        # Equilibrate system after evaporation
        run_equilibration "$tag" "step${tag}_post.gro" "step${tag}_post.top"
        
        log_message "Cycle $i completed successfully"
    done
    
    # Cleanup
    rm -f \#*
    
    # ========================================================================
    # FINAL ANNEALING
    # ========================================================================
    
    log_message ""
    log_message "========================================"
    log_message "STARTING FINAL ANNEALING"
    log_message "========================================"
    
    local final_cycle=$((CYCLES-1))
    local final_gro="step${final_cycle}_npt.gro"
    local final_cpt="step${final_cycle}_npt.cpt"
    local final_top="step${final_cycle}_post.top"
    
    log_message "Using files from cycle ${final_cycle}:"
    log_message "  - GRO: $final_gro"
    log_message "  - CPT: $final_cpt"
    log_message "  - TOP: $final_top"
    
    # Final height check
    check_and_fix_box_height "$final_gro" "$final_cycle"
    
    # Run annealing
    log_message ">>> Running annealing simulation..."
    gmx grompp -f "$MDP_ANNEAL" -c "$final_gro" -t "$final_cpt" -p "$final_top" \
               -o "${OUT_FILM}.tpr" -maxwarn 10 &>/dev/null || log_error "grompp failed (annealing)"
    gmx mdrun -deffnm "$OUT_FILM" -v || log_error "mdrun failed (annealing)"
    
    log_message ""
    log_message "========================================"
    log_message "SIMULATION COMPLETED SUCCESSFULLY!"
    log_message "========================================"
    log_message "Final film: ${OUT_FILM}"
}

# Execute main program
main "$@"

